//! `OmnigentHarness`: runs tasks through a local Omnigent install (ADR 4) in the one mode that
//! keeps the contributor's login away from task content (ADR 5, "Findings").
//!
//! The generated agent sets `os_env.sandbox.allow_network: false`. Omnigent then runs the AI
//! CLI *unwrapped*, with its native tools disabled, and routes all file and shell access
//! through its own sandboxed helpers (bwrap on Linux, Seatbelt on macOS) rooted at the task
//! workspace. The login stays with the trusted CLI process; task commands cannot see it.
//!
//! Omnigent's helpers, not the `togra` sandbox, isolate the task here, so this harness needs a
//! sandbox that exposes a host workspace directory (`dir` or `bwrap`). That fallback mode is not
//! a documented Omnigent setting, so the installed version is pinned and the probe in
//! `scripts/probe-omnigent-sandbox.py` should be re-run on upgrades.

use crate::harness::Harness;
use crate::context::{McpEntry, ProjectContext};
use crate::manifest::{TaskManifest, BRIDGE_SERVER_NAME};
use crate::meter::UsageMeter;
use crate::sandbox::Workspace;
use crate::{Error, Result};
use std::io::{BufRead, BufReader, Read};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::mpsc;
use std::time::{Duration, Instant};

pub struct OmnigentHarness {
    pub bin: String,
    /// Where the local Omnigent server answers (used only to read per-session token usage).
    pub server_url: String,
    /// Omnigent harness name, e.g. `claude-sdk` or `codex`.
    pub harness: String,
    /// Required `omnigent --version` prefix, e.g. `0.16.`.
    pub version_prefix: String,
    /// Per-task agent directories are created under here and removed after each run.
    pub agents_dir: PathBuf,
    pub poll: Duration,
}

/// Builds the agent config handed to Omnigent for one task. Everything comes from validated
/// fields and is emitted as JSON (valid YAML), so no task text is ever interpolated into YAML.
/// `skills: none` keeps the contributor's own skills out of the task; MCP entries have only a
/// URL, so there are no commands, headers or `${VAR}` expansion to abuse (ADR 9).
///
/// `bridge` selects the execution path (ADR 10):
/// - `Some(argv)`: the task runs in a container sandbox. The agent gets *no* `os_env` (so Omnigent
///   registers no host shell or file tools and keeps the CLI's native tools off) and its only
///   tools come from MCP servers that run inside the container, starting with the exec bridge.
///   `argv` is generated by the runner (`docker exec -i <container> /togra/mcp-exec`).
/// - `None`: Omnigent's own no-network sandbox helpers run the tools (ADR 5, "Findings").
pub fn agent_config(ctx: &ProjectContext, bridge: Option<&[String]>) -> String {
    let mut cfg = serde_json::json!({
        "spec_version": 1,
        "name": "togra-task",
        "description": "A task donated through togra",
        "executor": {"type": "omnigent", "config": {"harness": "claude-sdk"}},
        "skills": "none",
    });
    let mut tools = serde_json::Map::new();
    if bridge.is_some() {
        cfg["prompt"] = "You are completing one self-contained task for a public-good project. Your shell and file tools run in an isolated sandbox whose working directory is /workspace. Reply with the final result only.".into();
    } else {
        let sandbox = if cfg!(target_os = "macos") { "darwin_seatbelt" } else { "linux_bwrap" };
        cfg["prompt"] = "You are completing one self-contained task for a public-good project. Work only inside the current directory and reply with the final result only.".into();
        cfg["os_env"] = serde_json::json!({"type": "caller_process", "cwd": ".", "sandbox": {"type": sandbox, "write_paths": ["."], "allow_network": false}});
    }
    // Remote MCP servers only; command servers need a harness that can start them in the sandbox.
    for m in &ctx.mcp {
        if let McpEntry::Remote { name, url, .. } = m {
            tools.insert(name.clone(), serde_json::json!({"type": "mcp", "url": url}));
        }
    }
    // Inserted last so a project server can never replace the runner's own bridge.
    if let Some(argv) = bridge {
        tools.insert(BRIDGE_SERVER_NAME.into(), serde_json::json!({"type": "mcp", "command": argv[0], "args": &argv[1..]}));
    }
    if !tools.is_empty() {
        cfg["tools"] = tools.into();
    }
    serde_json::to_string_pretty(&cfg).expect("static json")
}

/// Writes `dir/config.yaml` and `dir/skills/<name>/...` for a task (the context is already parsed
/// and validated).
pub fn write_agent_dir(dir: &Path, ctx: &ProjectContext, bridge: Option<&[String]>) -> Result<()> {
    std::fs::create_dir_all(dir)?;
    std::fs::write(dir.join("config.yaml"), agent_config(ctx, bridge))?;
    for sk in &ctx.skills {
        for (path, data) in &sk.files {
            let target = dir.join("skills").join(&sk.name).join(path);
            std::fs::create_dir_all(target.parent().unwrap())?;
            std::fs::write(target, data)?;
        }
    }
    Ok(())
}

impl OmnigentHarness {
    pub fn new(state_dir: &Path) -> Result<Self> {
        let agents_dir = state_dir.join("agents");
        std::fs::create_dir_all(&agents_dir)?;
        Ok(Self {
            bin: "omnigent".into(),
            server_url: "http://127.0.0.1:6767".into(),
            harness: "claude-sdk".into(),
            version_prefix: "0.16.".into(),
            agents_dir,
            poll: Duration::from_secs(5),
        })
    }

    /// Fails unless the pinned Omnigent version is installed.
    pub fn check_version(&self) -> Result<()> {
        let out = Command::new(&self.bin).arg("--version").output().map_err(|e| Error::Harness(format!("cannot run `{}`: {e}", self.bin)))?;
        let v = String::from_utf8_lossy(&out.stdout);
        match v.split_whitespace().nth(1) {
            Some(ver) if ver.starts_with(&self.version_prefix) => Ok(()),
            _ => Err(Error::Harness(format!("unsupported Omnigent `{}`; need {}x", v.trim(), self.version_prefix))),
        }
    }

    /// Tokens used by a session so far: input + output + cache creation (cache reads are free
    /// to the quota and are excluded).
    fn session_tokens(&self, session: &str) -> Option<u64> {
        let url = format!("{}/v1/sessions/{session}", self.server_url.trim_end_matches('/'));
        let mut resp = ureq::get(&url).config().timeout_global(Some(Duration::from_secs(5))).build().call().ok()?;
        let v: serde_json::Value = serde_json::from_str(&resp.body_mut().read_to_string().ok()?).ok()?;
        let by_model = v.get("usage_by_model")?.as_object()?;
        let n = |m: &serde_json::Value, k: &str| m.get(k).and_then(|x| x.as_u64()).unwrap_or(0);
        Some(by_model.values().map(|m| n(m, "input_tokens") + n(m, "output_tokens") + n(m, "cache_creation_input_tokens")).sum())
    }
}

/// Extracts the session id from `Omnigent session: http://host/c/<id>`.
pub fn parse_session_id(line: &str) -> Option<String> {
    let rest = line.strip_prefix("Omnigent session:")?;
    let id = rest.rsplit("/c/").next()?.trim();
    (!id.is_empty() && id.chars().all(|c| c.is_ascii_alphanumeric())).then(|| id.to_string())
}

impl Harness for OmnigentHarness {
    fn probe(&self) -> Result<()> {
        self.check_version()
    }

    fn supports_context(&self) -> bool {
        true
    }

    fn run(&self, task: &TaskManifest, ctx: &ProjectContext, ws: &Workspace, meter: &mut UsageMeter) -> Result<String> {
        let bridge = ws.bridge_argv();
        if bridge.is_none() && ws.path.as_os_str().is_empty() {
            return Err(Error::Harness("the omnigent harness needs a host workspace (sandbox `dir` or `bwrap`) or a container sandbox with the exec bridge".into()));
        }
        if ctx.has_stdio_mcp() {
            return Err(Error::Harness("the omnigent harness cannot run MCP servers inside the sandbox".into()));
        }
        let agent_dir = self.agents_dir.join(DockerName::of(&task.id));
        write_agent_dir(&agent_dir, ctx, bridge.as_deref())?;
        let _cleanup = RemoveOnDrop(agent_dir.clone());
        let mut child = Command::new(&self.bin)
            .args(["run"])
            .arg(&agent_dir)
            .args(["--harness", &self.harness, "-p", &task.prompt])
            .current_dir(if bridge.is_some() { &agent_dir } else { &ws.path })
            .stdin(Stdio::null())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .map_err(|e| Error::Harness(format!("cannot run `{}`: {e}", self.bin)))?;

        let (id_tx, id_rx) = mpsc::channel::<String>();
        let mut stdout = child.stdout.take().unwrap();
        let out = std::thread::spawn(move || {
            let mut s = String::new();
            let _ = stdout.read_to_string(&mut s);
            s
        });
        let stderr = child.stderr.take().unwrap();
        let err = std::thread::spawn(move || {
            let mut text = String::new();
            for line in BufReader::new(stderr).lines().map_while(std::result::Result::ok) {
                if let Some(id) = parse_session_id(&line) {
                    let _ = id_tx.send(id);
                }
                text.push_str(&line);
                text.push('\n');
            }
            text
        });

        let deadline = Instant::now() + Duration::from_secs(task.sandbox_profile.timeout_secs);
        let (mut session, mut seen, mut next_poll) = (None::<String>, 0u64, Instant::now());
        let charge = |h: &Self, session: &Option<String>, seen: &mut u64, meter: &mut UsageMeter| -> Result<()> {
            if let Some(total) = session.as_deref().and_then(|s| h.session_tokens(s)) {
                if total > *seen {
                    let delta = total - *seen;
                    *seen = total;
                    meter.record(delta)?;
                }
            }
            Ok(())
        };
        let status = loop {
            if session.is_none() {
                session = id_rx.try_recv().ok();
            }
            if let Some(s) = child.try_wait()? {
                break s;
            }
            let stop = if Instant::now() >= deadline {
                Some(Error::Harness(format!("timed out after {}s", task.sandbox_profile.timeout_secs)))
            } else if Instant::now() >= next_poll {
                next_poll = Instant::now() + self.poll;
                charge(self, &session, &mut seen, meter).err()
            } else {
                None
            };
            if let Some(e) = stop {
                let _ = child.kill();
                let _ = child.wait();
                return Err(e);
            }
            std::thread::sleep(Duration::from_millis(50));
        };
        let (stdout, stderr) = (out.join().unwrap_or_default(), err.join().unwrap_or_default());
        if session.is_none() {
            session = id_rx.try_recv().ok();
        }
        charge(self, &session, &mut seen, meter)?; // final usage, may still abort the result
        if !status.success() {
            let tail: Vec<&str> = stderr.lines().rev().take(3).collect();
            return Err(Error::Harness(format!("omnigent exited with {status}: {}", tail.into_iter().rev().collect::<Vec<_>>().join(" | "))));
        }
        Ok(stdout.trim().to_string())
    }
}

struct RemoveOnDrop(PathBuf);
impl Drop for RemoveOnDrop {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

struct DockerName;
impl DockerName {
    /// Task id reduced to a safe single path component.
    fn of(id: &str) -> String {
        crate::sandbox::DockerSandbox::container_name(id)
    }
}
