//! `OmnigentHarness`: runs tasks through a local Omnigent install (ADR 4) in the one mode that
//! keeps the contributor's login away from task content (ADR 5, "Findings").
//!
//! The generated agent sets `os_env.sandbox.allow_network: false`. Omnigent then runs the AI
//! CLI *unwrapped*, with its native tools disabled, and routes all file and shell access
//! through its own sandboxed helpers (bwrap on Linux, Seatbelt on macOS) rooted at the task
//! workspace. The login stays with the trusted CLI process; task commands cannot see it.
//!
//! Omnigent's helpers, not the `toto` sandbox, isolate the task here, so this harness needs a
//! sandbox that exposes a host workspace directory (`dir` or `bwrap`). That fallback mode is not
//! a documented Omnigent setting, so the installed version is pinned and the probe in
//! `scripts/probe-omnigent-sandbox.py` should be re-run on upgrades.

use crate::harness::Harness;
use crate::context::{McpEntry, ProjectContext};
use crate::manifest::{TaskManifest, BRIDGE_SERVER_NAME};
use crate::meter::UsageMeter;
use crate::proxy::{AuthProxy, Provider};
use crate::sandbox::{Workspace, AGENT_DIR, PROXY_ADDR};
use crate::{Error, Result};
use std::io::{BufRead, BufReader, Read};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::{mpsc, Arc};
use std::time::{Duration, Instant};

/// Where Omnigent runs.
pub enum OmniPlacement {
    /// On the host (ADR 4, 5, 10).
    Host,
    /// Inside the task container, installed in the image with the project's tools and MCP servers,
    /// behind the credential proxy (ADR 12).
    Container { proxy: Arc<AuthProxy>, provider: Provider },
}

pub struct OmnigentHarness {
    pub bin: String,
    /// Where the local Omnigent server answers (used only to read per-session token usage).
    pub server_url: String,
    /// Omnigent harness name, e.g. `claude-sdk` or `codex`.
    pub harness: String,
    /// Required `omnigent --version` prefix, e.g. `0.16.`.
    pub version_prefix: String,
    /// Per-task agent directories are created under here and removed after each run.
    pub agents_dir: PathBuf,
    pub poll: Duration,
    pub placement: OmniPlacement,
    /// Model name for the agent's `executor.model`. Needed in container placement, where Omnigent
    /// cannot discover models from the provider.
    pub model: Option<String>,
    /// Omnigent `os_env.sandbox` spec used in container placement. `None` means `{type: none}`
    /// (the container is the sandbox); a bwrap spec with `egress_rules` needs the nested-userns
    /// seccomp profile and `bubblewrap` in the image.
    pub sandbox_spec: Option<serde_json::Value>,
}

/// Builds the agent config handed to Omnigent for one task. Everything comes from validated
/// fields and is emitted as JSON (valid YAML), so no task text is ever interpolated into YAML.
/// `skills: none` keeps the contributor's own skills out of the task; MCP entries have only a
/// URL, so there are no commands, headers or `${VAR}` expansion to abuse (ADR 9).
///
/// `bridge` selects the execution path (ADR 10):
/// - `Some(argv)`: the task runs in a container sandbox. The agent gets *no* `os_env` (so Omnigent
///   registers no host shell or file tools and keeps the CLI's native tools off) and its only
///   tools come from MCP servers that run inside the container, starting with the exec bridge.
///   `argv` is generated by the runner (`docker exec -i <container> /toto/mcp-exec`).
/// - `None`: Omnigent's own no-network sandbox helpers run the tools (ADR 5, "Findings").
pub fn agent_config(ctx: &ProjectContext, bridge: Option<&[String]>) -> String {
    let mut cfg = serde_json::json!({
        "spec_version": 1,
        "name": "toto-task",
        "description": "A task donated through toto",
        "executor": {"type": "omnigent", "config": {"harness": "claude-sdk"}},
        "skills": "none",
    });
    let mut tools = serde_json::Map::new();
    if bridge.is_some() {
        cfg["prompt"] = "You are completing one self-contained task for a public-good project. Your shell and file tools run in an isolated sandbox whose working directory is /workspace. Reply with the final result only.".into();
    } else {
        let sandbox = if cfg!(target_os = "macos") { "darwin_seatbelt" } else { "linux_bwrap" };
        cfg["prompt"] = "You are completing one self-contained task for a public-good project. Work only inside the current directory and reply with the final result only.".into();
        cfg["os_env"] = serde_json::json!({"type": "caller_process", "cwd": ".", "sandbox": {"type": sandbox, "write_paths": ["."], "allow_network": false}});
    }
    // Remote MCP servers only; command servers need a harness that can start them in the sandbox.
    for m in &ctx.mcp {
        if let McpEntry::Remote { name, url, .. } = m {
            tools.insert(name.clone(), serde_json::json!({"type": "mcp", "url": url}));
        }
    }
    // Inserted last so a project server can never replace the runner's own bridge.
    if let Some(argv) = bridge {
        tools.insert(BRIDGE_SERVER_NAME.into(), serde_json::json!({"type": "mcp", "command": argv[0], "args": &argv[1..]}));
    }
    if !tools.is_empty() {
        cfg["tools"] = tools.into();
    }
    serde_json::to_string_pretty(&cfg).expect("static json")
}

/// Agent config for Omnigent running inside the container: its own tools run in the container
/// (`sandbox: none`, the container is the sandbox) and project command servers start there too.
/// Project skills are found in `/workspace/.claude/skills`, where the runner unpacked them.
pub fn container_agent_config(ctx: &ProjectContext, harness: &str, model: Option<&str>, sandbox: Option<&serde_json::Value>) -> String {
    let mut cfg = serde_json::json!({
        "spec_version": 1,
        "name": "toto-task",
        "description": "A task donated through toto",
        "executor": {"type": "omnigent", "config": {"harness": harness}},
        "prompt": "You are completing one self-contained task for a public-good project. Work in the current directory and reply with the final result only.",
        "os_env": {"type": "caller_process", "cwd": ".", "sandbox": sandbox.cloned().unwrap_or_else(|| serde_json::json!({"type": "none"}))},
    });
    if let Some(m) = model {
        cfg["executor"]["model"] = m.into();
    }
    let tools: serde_json::Map<String, serde_json::Value> = ctx
        .mcp
        .iter()
        .filter_map(|m| match m {
            McpEntry::Stdio { name, command, args, env } => Some((name.clone(), serde_json::json!({"type": "mcp", "command": command, "args": args, "env": env}))),
            McpEntry::Remote { .. } => None,
        })
        .collect();
    if !tools.is_empty() {
        cfg["tools"] = tools.into();
    }
    serde_json::to_string_pretty(&cfg).expect("static json")
}

/// Writes `dir/config.yaml` and `dir/skills/<name>/...` for a task (the context is already parsed
/// and validated).
pub fn write_agent_dir(dir: &Path, ctx: &ProjectContext, bridge: Option<&[String]>) -> Result<()> {
    std::fs::create_dir_all(dir)?;
    std::fs::write(dir.join("config.yaml"), agent_config(ctx, bridge))?;
    for sk in &ctx.skills {
        for (path, data) in &sk.files {
            let target = dir.join("skills").join(&sk.name).join(path);
            std::fs::create_dir_all(target.parent().unwrap())?;
            std::fs::write(target, data)?;
        }
    }
    Ok(())
}

impl OmnigentHarness {
    /// Runs Omnigent inside the container behind `proxy` instead of on the host.
    pub fn in_container(mut self, proxy: Arc<AuthProxy>, provider: Provider) -> Self {
        self.placement = OmniPlacement::Container { proxy, provider };
        self
    }

    pub fn new(state_dir: &Path) -> Result<Self> {
        let agents_dir = state_dir.join("agents");
        std::fs::create_dir_all(&agents_dir)?;
        Ok(Self {
            bin: "omnigent".into(),
            server_url: "http://127.0.0.1:6767".into(),
            harness: "claude-sdk".into(),
            version_prefix: "0.16.".into(),
            agents_dir,
            poll: Duration::from_secs(5),
            placement: OmniPlacement::Host,
            model: None,
            sandbox_spec: None,
        })
    }

    /// Fails unless the pinned Omnigent version is installed.
    pub fn check_version(&self) -> Result<()> {
        let out = Command::new(&self.bin).arg("--version").output().map_err(|e| Error::Harness(format!("cannot run `{}`: {e}", self.bin)))?;
        let v = String::from_utf8_lossy(&out.stdout);
        match v.split_whitespace().nth(1) {
            Some(ver) if ver.starts_with(&self.version_prefix) => Ok(()),
            _ => Err(Error::Harness(format!("unsupported Omnigent `{}`; need {}x", v.trim(), self.version_prefix))),
        }
    }

    /// Tokens used by a session so far: input + output + cache creation (cache reads are free
    /// to the quota and are excluded).
    fn session_tokens(&self, session: &str) -> Option<u64> {
        let url = format!("{}/v1/sessions/{session}", self.server_url.trim_end_matches('/'));
        let mut resp = ureq::get(&url).config().timeout_global(Some(Duration::from_secs(5))).build().call().ok()?;
        let v: serde_json::Value = serde_json::from_str(&resp.body_mut().read_to_string().ok()?).ok()?;
        let by_model = v.get("usage_by_model")?.as_object()?;
        let n = |m: &serde_json::Value, k: &str| m.get(k).and_then(|x| x.as_u64()).unwrap_or(0);
        Some(by_model.values().map(|m| n(m, "input_tokens") + n(m, "output_tokens") + n(m, "cache_creation_input_tokens")).sum())
    }
}

/// Extracts the session id from `Omnigent session: http://host/c/<id>`.
pub fn parse_session_id(line: &str) -> Option<String> {
    let rest = line.strip_prefix("Omnigent session:")?;
    let id = rest.rsplit("/c/").next()?.trim();
    (!id.is_empty() && id.chars().all(|c| c.is_ascii_alphanumeric())).then(|| id.to_string())
}

impl Harness for OmnigentHarness {
    fn probe(&self) -> Result<()> {
        self.check_version()
    }

    fn supports_context(&self) -> bool {
        true
    }

    fn context_in_workspace(&self) -> bool {
        matches!(self.placement, OmniPlacement::Container { .. })
    }

    fn run(&self, task: &TaskManifest, ctx: &ProjectContext, ws: &Workspace, meter: &mut UsageMeter) -> Result<String> {
        if let OmniPlacement::Container { proxy, provider } = &self.placement {
            return self.run_in_container(task, ctx, ws, meter, proxy, *provider);
        }
        let bridge = ws.bridge_argv();
        if bridge.is_none() && ws.path.as_os_str().is_empty() {
            return Err(Error::Harness("the omnigent harness needs a host workspace (sandbox `dir` or `bwrap`) or a container sandbox with the exec bridge".into()));
        }
        if ctx.has_stdio_mcp() {
            return Err(Error::Harness("the omnigent harness cannot run MCP servers inside the sandbox".into()));
        }
        let agent_dir = self.agents_dir.join(DockerName::of(&task.id));
        write_agent_dir(&agent_dir, ctx, bridge.as_deref())?;
        let _cleanup = RemoveOnDrop(agent_dir.clone());
        let mut child = Command::new(&self.bin)
            .args(["run"])
            .arg(&agent_dir)
            .args(["--harness", &self.harness, "-p", &task.prompt])
            .current_dir(if bridge.is_some() { &agent_dir } else { &ws.path })
            .stdin(Stdio::null())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .map_err(|e| Error::Harness(format!("cannot run `{}`: {e}", self.bin)))?;

        let (id_tx, id_rx) = mpsc::channel::<String>();
        let mut stdout = child.stdout.take().unwrap();
        let out = std::thread::spawn(move || {
            let mut s = String::new();
            let _ = stdout.read_to_string(&mut s);
            s
        });
        let stderr = child.stderr.take().unwrap();
        let err = std::thread::spawn(move || {
            let mut text = String::new();
            for line in BufReader::new(stderr).lines().map_while(std::result::Result::ok) {
                if let Some(id) = parse_session_id(&line) {
                    let _ = id_tx.send(id);
                }
                text.push_str(&line);
                text.push('\n');
            }
            text
        });

        let deadline = Instant::now() + Duration::from_secs(task.sandbox_profile.timeout_secs);
        let (mut session, mut seen, mut next_poll) = (None::<String>, 0u64, Instant::now());
        let charge = |h: &Self, session: &Option<String>, seen: &mut u64, meter: &mut UsageMeter| -> Result<()> {
            if let Some(total) = session.as_deref().and_then(|s| h.session_tokens(s)) {
                if total > *seen {
                    let delta = total - *seen;
                    *seen = total;
                    meter.record(delta)?;
                }
            }
            Ok(())
        };
        let status = loop {
            if session.is_none() {
                session = id_rx.try_recv().ok();
            }
            if let Some(s) = child.try_wait()? {
                break s;
            }
            let stop = if Instant::now() >= deadline {
                Some(Error::Harness(format!("timed out after {}s", task.sandbox_profile.timeout_secs)))
            } else if Instant::now() >= next_poll {
                next_poll = Instant::now() + self.poll;
                charge(self, &session, &mut seen, meter).err()
            } else {
                None
            };
            if let Some(e) = stop {
                let _ = child.kill();
                let _ = child.wait();
                return Err(e);
            }
            std::thread::sleep(Duration::from_millis(50));
        };
        let (stdout, stderr) = (out.join().unwrap_or_default(), err.join().unwrap_or_default());
        if session.is_none() {
            session = id_rx.try_recv().ok();
        }
        charge(self, &session, &mut seen, meter)?; // final usage, may still abort the result
        if !status.success() {
            let tail: Vec<&str> = stderr.lines().rev().take(3).collect();
            return Err(Error::Harness(format!("omnigent exited with {status}: {}", tail.into_iter().rev().collect::<Vec<_>>().join(" | "))));
        }
        Ok(stdout.trim().to_string())
    }
}

impl OmnigentHarness {
    /// Runs `omnigent run` inside the container. The only credential there is a dummy; model calls
    /// reach the API through the relay and the proxy, which also does the metering.
    fn run_in_container(&self, task: &TaskManifest, ctx: &ProjectContext, ws: &Workspace, meter: &mut UsageMeter, proxy: &AuthProxy, provider: Provider) -> Result<String> {
        use crate::sandbox::exec_io;
        if ws.bridge_argv().is_none() {
            return Err(Error::Harness("omnigent container placement needs a container sandbox with the relay bridge".into()));
        }
        if ctx.mcp.iter().any(|m| matches!(m, McpEntry::Remote { .. })) {
            return Err(Error::Harness("remote MCP servers are unreachable from a container without network; use command servers".into()));
        }
        let (name, head) = ws.exec_prefix.split_last().expect("a container sandbox has an exec prefix");
        let with_env = |envs: &[(String, String)]| -> Workspace {
            let mut prefix: Vec<String> = head.to_vec();
            for (k, v) in envs {
                prefix.extend(["-e".into(), format!("{k}={v}")]);
            }
            prefix.extend(["-w".into(), "/workspace".into(), name.clone()]);
            Workspace { task_id: ws.task_id.clone(), path: ws.path.clone(), exec_prefix: prefix, bridge: true }
        };
        let base_url = format!("http://{PROXY_ADDR}");
        let mut envs: Vec<(String, String)> = vec![("HOME".into(), "/tmp/home".into()), ("TERM".into(), "dumb".into()), ("DISABLE_AUTOUPDATER".into(), "1".into()), ("PATH".into(), format!("{AGENT_DIR}:/usr/local/bin:/usr/bin:/bin"))];
        match provider {
            Provider::Anthropic => envs.extend([("ANTHROPIC_BASE_URL".into(), base_url), ("ANTHROPIC_AUTH_TOKEN".into(), "not-a-credential".into())]),
            Provider::OpenAi => envs.extend([("OPENAI_BASE_URL".into(), format!("{base_url}/v1")), ("OPENAI_API_KEY".into(), "not-a-credential".into())]),
        }
        let sh = with_env(&envs);
        // Agent config and prompt are written into the container; the prompt goes through a file so
        // it never appears in a process list or hits argument-length limits.
        let cfg = container_agent_config(ctx, &self.harness, self.model.as_deref(), self.sandbox_spec.as_ref());
        let t = Duration::from_secs(30);
        exec_io(&sh, &["sh", "-c", "mkdir -p /tmp/agent /tmp/home && cat > /tmp/agent/config.yaml"], Some(cfg.as_bytes()), t, 4096)?;
        exec_io(&sh, &["sh", "-c", "cat > /tmp/prompt.txt"], Some(task.prompt.as_bytes()), t, 4096)?;

        let start = proxy.tokens();
        let mut argv = sh.exec_prefix.clone();
        argv.extend(["sh".into(), "-c".into(), format!("exec omnigent run /tmp/agent --harness {} -p \"$(cat /tmp/prompt.txt)\"", shell_word(&self.harness))]);
        let mut child = Command::new(&argv[0]).args(&argv[1..]).stdin(Stdio::null()).stdout(Stdio::piped()).stderr(Stdio::piped()).spawn()?;
        let (mut so, mut se) = (child.stdout.take().unwrap(), child.stderr.take().unwrap());
        let out = std::thread::spawn(move || {
            let mut b = String::new();
            let _ = so.read_to_string(&mut b);
            b
        });
        let err = std::thread::spawn(move || {
            let mut b = String::new();
            let _ = se.read_to_string(&mut b);
            b
        });
        let deadline = Instant::now() + Duration::from_secs(task.sandbox_profile.timeout_secs);
        let mut charged = 0u64;
        let status = loop {
            if let Some(s) = child.try_wait()? {
                break s;
            }
            let used = proxy.tokens().saturating_sub(start);
            if used > charged {
                let delta = used - charged;
                charged = used;
                if let Err(e) = meter.record(delta) {
                    let _ = child.kill();
                    let _ = child.wait();
                    return Err(e);
                }
            }
            if Instant::now() >= deadline {
                let _ = child.kill();
                let _ = child.wait();
                return Err(Error::Harness(format!("timed out after {}s", task.sandbox_profile.timeout_secs)));
            }
            std::thread::sleep(Duration::from_millis(50));
        };
        let (stdout, stderr) = (out.join().unwrap_or_default(), err.join().unwrap_or_default());
        let used = proxy.tokens().saturating_sub(start);
        if used > charged {
            meter.record(used - charged)?;
        }
        if !status.success() {
            let hint = if status.code() == Some(127) { " (is `omnigent` installed in the sandbox image?)" } else { "" };
            let tail: Vec<&str> = stderr.lines().rev().take(3).collect();
            return Err(Error::Harness(format!("omnigent exited with {status}{hint}: {}", tail.into_iter().rev().collect::<Vec<_>>().join(" | "))));
        }
        Ok(stdout.trim().to_string())
    }
}

/// Harness names come from the contributor's config; refuse anything that is not a plain word.
fn shell_word(s: &str) -> &str {
    if !s.is_empty() && s.chars().all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_') { s } else { "claude-sdk" }
}

struct RemoveOnDrop(PathBuf);
impl Drop for RemoveOnDrop {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

struct DockerName;
impl DockerName {
    /// Task id reduced to a safe single path component.
    fn of(id: &str) -> String {
        crate::sandbox::DockerSandbox::container_name(id)
    }
}
